[package]
name = "futures-async-stream-internal-codegen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
fs-err = "2"
globset = { version = "0.4", default-features = false }
prettyplease = "0.2"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "visit-mut"] }

[lints]
workspace = true
