[package]
name = "futures-async-stream-internal-codegen"
edition = "2021"

[dependencies]
test-helper = { features = ["codegen"], git = "https://github.com/taiki-e/test-helper.git", rev = "c78a65c" }

[lints]
workspace = true
